version: '2'

services:
    transmission:
        build:
            context: .
            target: dev
        ports:
            - "51413:51413/tcp"
            - "51413:51413/udp"
        tmpfs:
            - /tmp
        volumes:
            - ${HOME}/dev/ds/data/torrent/downloads:/transmission/downloads:rw
            - ${HOME}/dev/docker/data/torrent/incompletes:/transmission/incompletes:rw
            #- /data/torrent/downloads:/transmission/downloads:rw
            #- /data/torrent/incompletes:/transmission/incompletes:rw
        restart: unless-stopped
        networks:
            - nginxproxygitdeploy_net-proxy

networks:
    nginxproxygitdeploy_net-proxy:
        external: true